vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.0.0/24"
availability_zone = "eu-west-1a"
env_prefix = "dev"
instance_type = "t2.medium"
ec2_user = "ec2-user"
private_key_file_path = "/home/viren/.ssh/terraform_key.pem"